version: '3'
services:
  zoo:
    image: zookeeper
    restart: always
    ports:
        - 2181:2181
    environment:
      ZOO_MY_ID: 1
      #ZOO_SERVERS: server.1=zoo:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
      ZOO_SERVERS: server.1=zoo:2888:3888 
